export const ASP_FRONTEND_URL = process.env.NEXT_PUBLIC_ASP_FRONTEND_URL
export const ASP_BACKEND_APP_URI = process.env.NEXT_PUBLIC_ASP_BACKEND_APP_URI
export const EMZ_FRONTEND_URL = process.env.NEXT_PUBLIC_EMZ_FRONTEND_URL
export const EMZ_BACKEND_APP_URI = process.env.NEXT_PUBLIC_EMZ_BACKEND_APP_URI
